all:bid card player score client

bid:Bid.java
	javac -cp /usr/local/lib/gson/gson-2.2.2.jar: Bid.java 

card:Card.java
	javac -cp /usr/local/lib/gson/gson-2.2.2.jar: Card.java 

player:Player.java
	javac -cp /usr/local/lib/gson/gson-2.2.2.jar: Player.java 

score:score.java
	javac -cp /usr/local/lib/gson/gson-2.2.2.jar: score.java 

client:client.java
	javac -cp /usr/local/lib/gson/gson-2.2.2.jar: client.java 
